### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sprouseamark** [OSU-CS361-W17/group19_project2#9]
Hey are you guys getting an error saying:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
?

I'm not exactly sure where it is coming from. Have you guys come across this before?

**Comment by Zaengled** [comment]
That is just us missing some debugging tool, the TA mentioned it in a canvas discussion. It shouldn't affect the program at all

**Comment by sprouseamark** [comment]
Right, I remember them saying that now. Thanks
